apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    name: hello
spec:
  containers:
  - name: hello
    image: localhost:5000/test/node
    ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: registrypullsecret