==== Pod

Démarrons par le plus petit élément à savoir le pod.

Le pod est constitué de 1 à n conteneur : dans la pratique on limite à 1 conteneur par pod.

1) Création du premier pod (en version Ligne de commande): 

[source,console]
----
kubectl run whoami --image=whoami:latest --port=80 --generator=run-pod/v1
----


On vérifie via la commande

[source,console]
----
kubectl get po
----

(_Description de la commande_)

TIP: _po_ est un nom court de pod. on peut écrire soit _po_ soit _pod_. 
<<_nom_court_des_ressources_kubernetes,nom court des ressources Kubernetes>>

On doit obtenir

[source,console]
----
NAME      READY     STATUS    RESTARTS   AGE
whoami    1/1       Running   0          9m
----


2) Réalisons la même commande mais via un fichier yaml.

On supprime d'abord le pod fraîchement créé.

[source,console]
----
kubectl delete po whoami
----

et on crée le nouveau à l'aide du fichier yaml "pod.yaml" que l'on va lui aussi créer

[source,console]
----
cat > pod.yaml << eof
apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: whoami:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
eof
kubectl apply -f pod.yaml
----

On vérifie que le pod est créé et qu'il est opérationnel

[source,console]
----
kubectl get po
----

On doit obtenir

[source,console]
----
NAME      READY     STATUS    RESTARTS   AGE
whoami    1/1       Running   0          9m
----

Il est possible de définir des ressources au niveau du pod qui seront nécessaires au bon fonctionnement et qui pourra être nécessaire dans le choix du noeud exécutant le pod.

Il est aussi possible de définir une valeur limite qui pourrait engendrer l'arrêt du pod si celui-ci les dépasse.

un exemple :

[source,console]
----
kubectl delete pod whoami
cat > pod-resource.yaml << eof
apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: whoami:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: 100M
        cpu: "0.1"
      limits:
        memory: 150M
        cpu: "0.4"
eof
kubectl apply -f pod-resource.yaml
----

Il existe aussi au niveau du pod 2 sondes essentiels permettant de vérifier l'état du pod ou de garantir que celui est prêt.
Il s'agit des sondes suivantes :

* LivenessProbe : indique si le conteneur est en cours d'exécution
* ReadinessProbe : indique si le conteneur est prêt à recevoir du traffic

NOTE: il existe une troisième sonde (startupProbe) orientée pour des applications legacy ou lourdes qui requière un temps de démarrage conséquent. Cette sonde désactive toutes les sondes tant que le contenuer n'est pas démarré.

Voici un exemple:

[source,console]
----
kubectl delete pod whoami
cat > pod-probe.yaml << eof
apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: whoami:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
        name: whoami-port
    resources:
        requests:
          memory: 100M
          cpu: "0.1"
        limits:
          memory: 150M
          cpu: "0.4"
    livenessProbe:
      httpGet:
        path: /
        port: whoami-port
      initialDelaySeconds: 2
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: whoami-port
      initialDelaySeconds: 2
      periodSeconds: 3
eof
kubectl apply -f pod-probe.yaml
----