apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: whoami:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
        name: whoami-port
    resources:
        requests:
          memory: 100M
          cpu: "0.1"
        limits:
          memory: 150M
          cpu: "0.4"
    livenessProbe:
      httpGet:
        path: /
        port: whoami-port
      initialDelaySeconds: 2
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: whoami-port
      initialDelaySeconds: 2
      periodSeconds: 3
