apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    name: whoami
spec:
  containers:
  - name: whoami
    image: whoami:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
        name: whoami-port
