apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    name: hello
spec:
  containers:
  - name: hello
    image: jufab/whoami
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
        name: hello-port
