==== Service

Un service est une ressource permettant d'accéder à un ensemble de pods défini par un sélecteur.

Un service va permettre d'exposer des pods et pouvoir y accéder sans que l'on est besoin d'avoir la moindre information au sujet des pods qu'il expose.

Le sélecteur des pods dans le service va se définir via des labels que les pods possèdent.

Le service va permettre aussi d'exposer celui-ci sur un port différent de celui du pod

1) On crée un service via un fichier "service.yaml"

[source,console]
----
cat > service.yaml << eof
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
eof
kubectl apply -f service.yaml
----

2) On vérifie la création de ce service via

[source,console]
----
kubectl get svc
----

qui nous donnera

[source,console]
----
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP   17m
whoami       ClusterIP   10.108.134.96   <none>        80/TCP    11s
----


Comment ça marche un service?

Le service pointe vers un endpoint. Le endpoint rafraichit régulièrement la liste des IP des pods correspondant au sélecteur.
Le service a ainsi l'ensemble des adresses ip des pods pour communiquer.

Pour visualiser un endpoint : 

[source,console]
----
kubectl get endpoints whoami
----

donnera :
[source,console]
----
NAME      ENDPOINTS                   AGE
whoami    10.44.0.1:80,10.44.0.2:80   2m
----

---

Dans la description, il manque une information au niveau ".spec.type" qui permet de spécifier le type du service. 

Il existe trois types: 

* ClusterIP : service non exposé en dehors du cluster, mais accessible par les membres du cluster
* NodePort : réserve un port qui sera appliqué à l'ensemble du cluster (réservation) généralement entre 30000 - 32767
* LoadBalancer : provisionne une adresse IP externe par l'intermédiaire de la plateforme.

---

Type LoadBalancer

[source,console]
----
cat > service-loadbalancer.yaml << eof
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
eof
kubectl apply -f service-loadbalancer.yaml
----


[source,console]
----
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP        46m
whoami       LoadBalancer   10.109.74.243   <pending>     80:31592/TCP   11s
----

NOTE: Si la plateforme (comme c'est le cas ici) n'a pas de service permettant d'obtenir une adresse externe, alors elle reste à l'état pending.


Type NodePort : 

[source,console]
----
cat > service-nodeport.yaml << eof
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: NodePort
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
eof
kubectl apply -f service-nodeport.yaml
----


[source,console]
----
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        39m
whoami       NodePort    10.109.63.115   <none>        80:31178/TCP   34m
----

On peut accéder à la ressource via l'url externe + le port attribué par NodePort.
Dans l'exemple au-dessus il s'agit du port 31178

