=== Créer notre première image et conteneur

Utilisation du projet "whoami" dans le dossier "docker".

1) Lancer le docker lab

-> [#lab-docker]#Voir le lab Docker#

2) Après authentification, création de l'instance "Create instance"

3) lancer la commande dans le terminal

[source,console]
----
docker version
----

pour s'assurer que docker est bien présent

4) copier le contenu du fichier index.js et l'intégrer dans le cluster via le terminal (voir astuce pour écrire un fichier)

(_Description du contenu du fichier_)


5) copier le contenu du fichier Dockerfile et l'intégrer dans le cluster via le terminal

(_Description du contenu du fichier_)

6) lancer la commande

[source,console]
----
docker build -t whoami . 
----

(_Description de la commande_)

L'image se créé à partir du contenu décrit dans le Dockerfile

on peut vérifier la présence de l'image via la commande

[source,console]
----
docker images
----

7) Lancer la commande

[source,console]
----
docker run -d -p 80:80 --name whoami whoami
----

(_Description de la commande_)

On peut vérifier que le container est opérationnel via la commande

[source,console]
----
docker ps
----

8) On vérifie l'accès à l'application :

Un petit "80" s'affiche au dessus du terminal. il permet d'accéder à notre serveur web fraichement deployé

On peut aussi vérifier en ligne de commande que le hostname correspond bien à celui qui s'affiche via la commande :

[source,console]
----
docker inspect --format '{{ .Config.Hostname}}' whoami
----

(_Description de la commande_)

*Conclusion*

Nous avons appris des commandes docker qui servent à

* Afficher la version docker
* Créer et tagguer une image docker
* Afficher la liste des images présentes sur la machine
* Instancier un conteneur
* Lister les conteneurs en cours d'exécution
* Inspecter un conteneur en cours d'exécution
